FROM flink:1.17-scala_2.12

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

COPY flink/requirements.txt /opt/flink-job/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/flink-job/requirements.txt

WORKDIR /opt/flink-job
COPY flink/ /opt/flink-job/

CMD ["python3", "/opt/flink-job/flink_trend_topics.py"]
